package POJOS;
// Generated 24 may. 2024 23:15:23 by Hibernate Tools 4.3.1



/**
 * RelContribuyenteOrdenanza generated by hbm2java
 */
public class RelContribuyenteOrdenanza  implements java.io.Serializable {


     private Integer id;
     private Contribuyente contribuyente;
     private Ordenanza ordenanza;

    public RelContribuyenteOrdenanza() {
    }

    public RelContribuyenteOrdenanza(Contribuyente contribuyente, Ordenanza ordenanza) {
       this.contribuyente = contribuyente;
       this.ordenanza = ordenanza;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Contribuyente getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(Contribuyente contribuyente) {
        this.contribuyente = contribuyente;
    }
    public Ordenanza getOrdenanza() {
        return this.ordenanza;
    }
    
    public void setOrdenanza(Ordenanza ordenanza) {
        this.ordenanza = ordenanza;
    }




}


